# -*- coding: utf-8 -*-
"""Copy of Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U-d7uYIB_aXCswhSIa0AVAwJgl_98XxZ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import os
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# ----------- Dataset Path -----------
DATASET_PATH = "2port dataset 1000.xlsx"

# ----------- Load Excel Dataset -----------
df = pd.read_excel(DATASET_PATH)
df.columns = df.columns.str.strip()

print("=" * 50)
print("         DATASET INFO")
print("=" * 50)
print(f"Total rows loaded : {len(df)}")
print(f"Columns           : {list(df.columns)}")
print("=" * 50)

# ----------- Features and Targets -----------
X = df[['r2']].values
y = df[['port1', 'port2']].values

# ----------- Train Random Forest -----------
print("\nTraining Random Forest Model...")

model = MultiOutputRegressor(
    RandomForestRegressor(
        n_estimators=200,
        random_state=42
    )
)

model.fit(X, y)
print("Training complete.")

# ----------- Predictions -----------
y_pred = model.predict(X)

# ----------- Evaluation Metrics -----------
mse = mean_squared_error(y, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y, y_pred)
r2 = r2_score(y, y_pred)
accuracy = r2 * 100

print("\n" + "=" * 50)
print("       Model Evaluation")
print("=" * 50)
print(f"Total samples : {len(df)}")
print(f"MSE           : {mse:.6f}")
print(f"RMSE          : {rmse:.6f}")
print(f"MAE           : {mae:.6f}")
print(f"R² Score      : {r2:.6f}")
print(f"Accuracy      : {accuracy:.2f}%")
print("=" * 50)

# ----------- Save Model -----------
os.makedirs("model", exist_ok=True)
joblib.dump(model, "model/rf_model_2port.pkl")

print("\nModel saved to 'model/rf_model_2port.pkl'")

# ----------- Predicted vs Actual Table -----------
result_df = pd.DataFrame(
    y_pred,
    columns=['port1_pred', 'port2_pred']
)

result_df[['port1_actual', 'port2_actual']] = df[['port1', 'port2']].values

result_df = pd.concat([df[['r2']].reset_index(drop=True), result_df], axis=1)

print("\nPredicted vs Actual Table (First 10 rows)")
print(result_df.head(10).to_string(index=False))

# ----------- Plot Predicted vs Actual -----------
ports = ['port1', 'port2']
sample_idx = np.arange(len(df))

plt.figure(figsize=(12,6))

for i, port in enumerate(ports,1):

    plt.subplot(1,2,i)

    actual = df[port].values
    predicted = result_df[f'{port}_pred'].values

    plt.plot(sample_idx, actual, 'o-', label="Actual", markersize=2)
    plt.plot(sample_idx, predicted, 'x--', label="Predicted", markersize=2)

    plt.title(f"{port} Actual vs Predicted")
    plt.xlabel("Sample Index")
    plt.ylabel("Value")
    plt.legend()
    plt.grid(True)

plt.tight_layout()
plt.savefig("model/training_plot_2port.png", dpi=150)
plt.show()

print("\nTraining plot saved to 'model/training_plot_2port.png'")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import os

from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# ----------- Dataset Path -----------
DATASET_PATH = "2port dataset 1000.xlsx"

# ----------- Load Excel Dataset -----------
df = pd.read_excel(DATASET_PATH)
df.columns = df.columns.str.strip()

print("=" * 50)
print("         DATASET INFO")
print("=" * 50)
print(f"Total rows loaded : {len(df)}")
print(f"Columns           : {list(df.columns)}")
print("=" * 50)

# ----------- Features and Targets -----------
X = df[['r2']].values
y = df[['port1', 'port2']].values

# ----------- Train AdaBoost Model -----------
print("\nTraining AdaBoost Model...")

base_model = DecisionTreeRegressor(max_depth=4)

model = MultiOutputRegressor(
    AdaBoostRegressor(
        estimator=base_model,
        n_estimators=200,
        learning_rate=0.1,
        random_state=42
    )
)

model.fit(X, y)
print("Training complete.")

# ----------- Make Predictions -----------
y_pred = model.predict(X)

# ----------- Evaluation Metrics -----------
mse = mean_squared_error(y, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y, y_pred)
r2 = r2_score(y, y_pred)
accuracy = r2 * 100

print("\n" + "=" * 50)
print("       Model Evaluation")
print("=" * 50)
print(f"Total samples : {len(df)}")
print(f"MSE           : {mse:.6f}")
print(f"RMSE          : {rmse:.6f}")
print(f"MAE           : {mae:.6f}")
print(f"R² Score      : {r2:.6f}")
print(f"Accuracy      : {accuracy:.2f}%")
print("=" * 50)

# ----------- Save Model -----------
os.makedirs("model", exist_ok=True)
joblib.dump(model, "model/adaboost_model_2port.pkl")

print("\nModel saved to 'model/adaboost_model_2port.pkl'")

# ----------- Predicted vs Actual Table -----------

result_df = pd.DataFrame(
    y_pred,
    columns=['port1_pred', 'port2_pred']
)

result_df[['port1_actual', 'port2_actual']] = df[['port1', 'port2']].values

result_df = pd.concat([df[['r2']].reset_index(drop=True), result_df], axis=1)

print("\nPredicted vs Actual Table (First 10 rows)")
print(result_df.head(10).to_string(index=False))

# ----------- Plot Predicted vs Actual -----------

ports = ['port1', 'port2']
sample_idx = np.arange(len(df))

plt.figure(figsize=(12,6))

for i, port in enumerate(ports,1):

    plt.subplot(1,2,i)

    actual = df[port].values
    predicted = result_df[f'{port}_pred'].values

    plt.plot(sample_idx, actual, 'o-', label="Actual", markersize=2)
    plt.plot(sample_idx, predicted, 'x--', label="Predicted", markersize=2)

    plt.title(f"{port} Actual vs Predicted")
    plt.xlabel("Sample Index")
    plt.ylabel("Value")
    plt.legend()
    plt.grid(True)

plt.tight_layout()
plt.savefig("model/adaboost_training_plot_2port.png", dpi=150)
plt.show()

print("\nTraining plot saved to 'model/adaboost_training_plot_2port.png'")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import os

from sklearn.multioutput import MultiOutputRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.preprocessing import StandardScaler

DATASET_PATH = "2port dataset 1000.xlsx"

# ----------- Load Excel Dataset -----------
df = pd.read_excel(DATASET_PATH)
df.columns = df.columns.str.strip()

print("=" * 50)
print("         DATASET INFO")
print("=" * 50)
print(f"Total rows loaded : {len(df)}")
print(f"Columns           : {list(df.columns)}")
print("=" * 50)

# ----------- Features and Targets -----------
X = df[['r2']].values
y = df[['port1', 'port2']].values

# ----------- Feature Scaling (Important for SVM) -----------
scaler = StandardScaler()
X = scaler.fit_transform(X)

# ----------- Train SVM Model -----------
print("\nTraining SVM Model...")

model = MultiOutputRegressor(
    SVR(
        kernel='rbf',
        C=100,
        gamma='scale',
        epsilon=0.01
    )
)

model.fit(X, y)

print("Training complete.")

# ----------- Make Predictions -----------
y_pred = model.predict(X)

# ----------- Evaluation Metrics -----------
mse      = mean_squared_error(y, y_pred)
rmse     = np.sqrt(mse)
mae      = mean_absolute_error(y, y_pred)
r2       = r2_score(y, y_pred)
accuracy = r2 * 100

print("\n" + "=" * 50)
print("       Model Evaluation on Training Data")
print("=" * 50)
print(f"Total samples : {len(df)}")
print(f"MSE           : {mse:.6f}")
print(f"RMSE          : {rmse:.6f}")
print(f"MAE           : {mae:.6f}")
print(f"R² Score      : {r2:.6f}")
print(f"Accuracy      : {accuracy:.2f}%")
print("=" * 50)

# ----------- Save Model -----------
os.makedirs("model", exist_ok=True)
joblib.dump(model, "model/svm_model_2port.pkl")

print("\nModel saved to 'model/svm_model_2port.pkl'")

# ----------- Predicted vs Actual Table -----------

result_df = pd.DataFrame(
    y_pred,
    columns=['port1_pred', 'port2_pred']
)

result_df[['port1_actual', 'port2_actual']] = \
    df[['port1', 'port2']].values

result_df = pd.concat([df[['r2']].reset_index(drop=True), result_df], axis=1)

print(f"\nPredicted vs Actual Table (first 10 of {len(result_df)} rows):")
print(result_df.head(10).to_string(index=False))

# ----------- Plot Predicted vs Actual -----------

ports = ['port1', 'port2']
sample_idx = np.arange(len(df))

plt.figure(figsize=(12,6))

for i, port in enumerate(ports,1):

    plt.subplot(1,2,i)

    actual = df[port].values
    predicted = result_df[f'{port}_pred'].values

    plt.plot(sample_idx, actual, 'o-', label='Actual', markersize=2, linewidth=1)
    plt.plot(sample_idx, predicted, 'x--', label='Predicted', markersize=2, linewidth=1)

    plt.title(f"{port} → Actual vs Predicted (n={len(df)})")
    plt.xlabel("Sample Index")
    plt.ylabel("Value")
    plt.legend()
    plt.grid(True, alpha=0.4)

plt.tight_layout()
plt.savefig("model/svm_training_plot_2port.png", dpi=150)
plt.show()

print("\nTraining plot saved to 'model/svm_training_plot_2port.png'")
print("Run 'predict.py' to make predictions using the saved model.")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import os

from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

DATASET_PATH = "2port dataset 1000.xlsx"

# ----------- Load Excel Dataset -----------
df = pd.read_excel(DATASET_PATH)
df.columns = df.columns.str.strip()

print("=" * 50)
print("         DATASET INFO")
print("=" * 50)
print(f"Total rows loaded : {len(df)}")
print(f"Columns           : {list(df.columns)}")
print("=" * 50)

# ----------- Features and Targets -----------
X = df[['r2']].values
y = df[['port1', 'port2']].values

# ----------- Train Linear Regression Model -----------
print("\nTraining Linear Regression Model...")

model = MultiOutputRegressor(
    LinearRegression()
)

model.fit(X, y)

print("Training complete.")

# ----------- Make Predictions -----------
y_pred = model.predict(X)

# ----------- Evaluation Metrics -----------
mse      = mean_squared_error(y, y_pred)
rmse     = np.sqrt(mse)
mae      = mean_absolute_error(y, y_pred)
r2       = r2_score(y, y_pred)
accuracy = r2 * 100

print("\n" + "=" * 50)
print("       Model Evaluation")
print("=" * 50)
print(f"Total samples : {len(df)}")
print(f"MSE           : {mse:.6f}")
print(f"RMSE          : {rmse:.6f}")
print(f"MAE           : {mae:.6f}")
print(f"R² Score      : {r2:.6f}")
print(f"Accuracy      : {accuracy:.2f}%")
print("=" * 50)

# ----------- Save Model -----------
os.makedirs("model", exist_ok=True)
joblib.dump(model, "model/linear_model_2port.pkl")

print("\nModel saved to 'model/linear_model_2port.pkl'")

# ----------- Predicted vs Actual Table -----------

result_df = pd.DataFrame(
    y_pred,
    columns=['port1_pred', 'port2_pred']
)

result_df[['port1_actual', 'port2_actual']] = \
    df[['port1', 'port2']].values

result_df = pd.concat([df[['r2']].reset_index(drop=True), result_df], axis=1)

print(f"\nPredicted vs Actual Table (first 10 rows):")
print(result_df.head(10).to_string(index=False))

# ----------- Plot Predicted vs Actual -----------

ports = ['port1', 'port2']
sample_idx = np.arange(len(df))

plt.figure(figsize=(12,6))

for i, port in enumerate(ports,1):

    plt.subplot(1,2,i)

    actual = df[port].values
    predicted = result_df[f'{port}_pred'].values

    plt.plot(sample_idx, actual, 'o-', label='Actual', markersize=2, linewidth=1)
    plt.plot(sample_idx, predicted, 'x--', label='Predicted', markersize=2, linewidth=1)

    plt.title(f"{port} → Actual vs Predicted (n={len(df)})")
    plt.xlabel("Sample Index")
    plt.ylabel("Value")
    plt.legend()
    plt.grid(True, alpha=0.4)

plt.tight_layout()
plt.savefig("model/linear_training_plot_2port.png", dpi=150)
plt.show()

print("\nTraining plot saved to 'model/linear_training_plot_2port.png'")
print("Run 'predict.py' to make predictions using the saved model.")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import os

from sklearn.multioutput import MultiOutputRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.preprocessing import StandardScaler

DATASET_PATH = "2port dataset 1000.xlsx"

# ----------- Load Excel Dataset -----------
df = pd.read_excel(DATASET_PATH)
df.columns = df.columns.str.strip()

print("=" * 50)
print("         DATASET INFO")
print("=" * 50)
print(f"Total rows loaded : {len(df)}")
print(f"Columns           : {list(df.columns)}")
print("=" * 50)

# ----------- Features and Targets -----------
X = df[['r2']].values
y = df[['port1', 'port2']].values

# ----------- Feature Scaling (Important for KNN) -----------
scaler = StandardScaler()
X = scaler.fit_transform(X)

# ----------- Train KNN Model -----------
print("\nTraining KNN Model...")

model = MultiOutputRegressor(
    KNeighborsRegressor(
        n_neighbors=5,
        weights='distance'
    )
)

model.fit(X, y)

print("Training complete.")

# ----------- Make Predictions -----------
y_pred = model.predict(X)

# ----------- Evaluation Metrics -----------
mse      = mean_squared_error(y, y_pred)
rmse     = np.sqrt(mse)
mae      = mean_absolute_error(y, y_pred)
r2       = r2_score(y, y_pred)
accuracy = r2 * 100

print("\n" + "=" * 50)
print("       Model Evaluation")
print("=" * 50)
print(f"Total samples : {len(df)}")
print(f"MSE           : {mse:.6f}")
print(f"RMSE          : {rmse:.6f}")
print(f"MAE           : {mae:.6f}")
print(f"R² Score      : {r2:.6f}")
print(f"Accuracy      : {accuracy:.2f}%")
print("=" * 50)

# ----------- Save Model -----------
os.makedirs("model", exist_ok=True)
joblib.dump(model, "model/knn_model_2port.pkl")

print("\nModel saved to 'model/knn_model_2port.pkl'")

# ----------- Predicted vs Actual Table -----------

result_df = pd.DataFrame(
    y_pred,
    columns=['port1_pred', 'port2_pred']
)

result_df[['port1_actual', 'port2_actual']] = \
    df[['port1', 'port2']].values

result_df = pd.concat([df[['r2']].reset_index(drop=True), result_df], axis=1)

print(f"\nPredicted vs Actual Table (first 10 rows):")
print(result_df.head(10).to_string(index=False))

# ----------- Plot Predicted vs Actual -----------

ports = ['port1', 'port2']
sample_idx = np.arange(len(df))

plt.figure(figsize=(12,6))

for i, port in enumerate(ports,1):

    plt.subplot(1,2,i)

    actual = df[port].values
    predicted = result_df[f'{port}_pred'].values

    plt.plot(sample_idx, actual, 'o-', label='Actual', markersize=2, linewidth=1)
    plt.plot(sample_idx, predicted, 'x--', label='Predicted', markersize=2, linewidth=1)

    plt.title(f"{port} → Actual vs Predicted (n={len(df)})")
    plt.xlabel("Sample Index")
    plt.ylabel("Value")
    plt.legend()
    plt.grid(True, alpha=0.4)

plt.tight_layout()
plt.savefig("model/knn_training_plot_2port.png", dpi=150)
plt.show()

print("\nTraining plot saved to 'model/knn_training_plot_2port.png'")
print("Run 'predict.py' to make predictions using the saved model.")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import os

# ___________Loading the model
MODEL_PATH   = "model/rf_model_2port.pkl"
DATASET_PATH = "2port dataset 1000.xlsx"

if not os.path.exists(MODEL_PATH):
    print("=" * 50)
    print("   Model not found!")
    print("  Please run 'train.py' first.")
    print("=" * 50)
    exit()

model = joblib.load(MODEL_PATH)
print("=" * 50)
print("   Model loaded from 'model/rf_model_2port.pkl'")
print("=" * 50)

# ___________Load training dataset for plotting
df_train = None
if os.path.exists(DATASET_PATH):
    df_train = pd.read_excel(DATASET_PATH)
    df_train.columns = df_train.columns.str.strip()

# ___________Trained r2 range (auto-derived from dataset)
if df_train is not None:
    R2_MIN = df_train['r2'].min()
    R2_MAX = df_train['r2'].max()
else:
    R2_MIN = 0.02   # fallback defaults
    R2_MAX = 0.30

print(f"  Trained r2 range : [{R2_MIN} – {R2_MAX}]")

PORTS = ['port1', 'port2']

# ___________Prediction function
def predict_ports(r2_val):
    """Run model prediction for a single r2 value and display results."""
    user_X      = np.array([[r2_val]])
    predictions = model.predict(user_X)[0]   # shape: (2,)

    print("\n" + "=" * 50)
    print("         PORT PREDICTION RESULTS")
    print("=" * 50)
    print(f"  Input r2       : {r2_val}")
    print("-" * 50)
    print(f"  {'Port':<12} {'Predicted Value':>20}")
    print("-" * 50)
    for port, val in zip(PORTS, predictions):
        print(f"  {port.capitalize():<12} {val:>20.6f}")
    print("=" * 50)
    return predictions


# ___________Plotting the predicted result
def plot_prediction(r2_val, predictions):
    """Plot predicted values against training data curves for both ports."""
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    fig.suptitle(
        f"2-Port Power Combiner  |  r2 = {r2_val}",
        fontsize=13, fontweight='bold'
    )

    for i, (port, pred_val) in enumerate(zip(PORTS, predictions)):
        ax = axes[i]

        if df_train is not None:
            df_sorted = df_train.sort_values('r2')
            ax.plot(df_sorted['r2'].values, df_sorted[port].values,
                    color='steelblue', alpha=0.6, linewidth=1.5,
                    label='Training data')

        # Green vertical line at the input r2
        ax.axvline(r2_val, color='green', linewidth=1.5,
                   linestyle=':', label=f'r2 = {r2_val}')

        # Red horizontal dashed line at the predicted value level
        ax.axhline(pred_val, color='red', linewidth=1.5,
                   linestyle='--', alpha=0.5, label=f'Predicted: {pred_val:.4f}')

        # Red dot at the exact predicted point (intersection)
        ax.plot(r2_val, pred_val,
                'o', color='red', markersize=10, zorder=5,
                label=f'▶ Point: ({r2_val}, {pred_val:.4f})')

        # Annotate the dot with its value
        ax.annotate(f'  {pred_val:.4f}',
                    xy=(r2_val, pred_val),
                    fontsize=9, color='red', fontweight='bold', va='bottom')

        ax.set_title(f"{port.capitalize()} — Training Data vs Predicted Point")
        ax.set_xlabel("r2")
        ax.set_ylabel(f"{port.capitalize()} Value")
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.4)

    plt.tight_layout()
    os.makedirs("plots", exist_ok=True)
    save_path = "plots/user_prediction_2port.png"
    plt.savefig(save_path, dpi=150)
    plt.show()
    plt.pause(0.1)
    print(f"   Plot saved to '{save_path}'")


# ___________Batch prediction from CSV/Excel
def predict_from_file(file_path):
    """Batch predict from a CSV or Excel file containing an r2 column."""
    if not os.path.exists(file_path):
        print(f"   File not found: {file_path}")
        return

    ext = os.path.splitext(file_path)[1].lower()
    if ext in ['.xlsx', '.xls']:
        batch_df = pd.read_excel(file_path)
    elif ext == '.csv':
        batch_df = pd.read_csv(file_path)
    else:
        print("   Unsupported file format. Please provide a .csv or .xlsx file.")
        return

    batch_df.columns = batch_df.columns.str.strip()

    if 'r2' not in batch_df.columns:
        print("   File must contain an 'r2' column.")
        return

    out_of_range = batch_df[
        (batch_df['r2'] < R2_MIN) | (batch_df['r2'] > R2_MAX)
    ]
    if len(out_of_range) > 0:
        print(f"\n   Warning: {len(out_of_range)} rows have r2 outside"
              f" trained range [{R2_MIN} – {R2_MAX}]. Predictions may be inaccurate.")

    X_batch = batch_df[['r2']].values
    preds   = model.predict(X_batch)   # shape: (n_rows, 2)

    output_df = batch_df[['r2']].copy()
    for i, port in enumerate(PORTS):
        output_df[f'{port}_pred'] = preds[:, i]

    os.makedirs("model", exist_ok=True)
    save_path = "model/batch_predictions_2port.csv"
    output_df.to_csv(save_path, index=False)

    print(f"\n   Batch predictions saved to '{save_path}'")
    print(output_df.to_string(index=False))


# ___________Main menu
while True:
    print("\n  Options:")
    print("    [1] Single prediction  (enter r2 manually)")
    print("    [2] Batch prediction   (load a CSV or Excel file)")
    print("    [3] Exit")

    choice = input("\nSelect option (1 / 2 / 3): ").strip()

    if choice == '1':
        while True:
            r2_input = input("\n  Enter r2 value (or 'back' to return): ").strip()
            if r2_input.lower() == 'back':
                break
            try:
                r2_val = float(r2_input)
            except ValueError:
                print("  Invalid value. Please enter a number.")
                continue

            if not (R2_MIN <= r2_val <= R2_MAX):
                print(f"\n  Warning: r2={r2_val} is outside the trained range"
                      f" [{R2_MIN} – {R2_MAX}]. Prediction may be inaccurate.")

            predictions = predict_ports(r2_val)

            show_plot = input("\n  Show prediction plot? (y/n): ").strip().lower()
            if show_plot == 'y':
                plot_prediction(r2_val, predictions)
                plt.close('all')

            again = input("\n  Predict again? (y/n): ").strip().lower()
            if again != 'y':
                break

    elif choice == '2':
        file_path = input("\n  Enter path to CSV or Excel file: ").strip()
        predict_from_file(file_path)

    elif choice == '3':
        print("\n  Goodbye!")
        break

    else:
        print("  Invalid choice. Please enter 1, 2, or 3.")