# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zq92tNGe_rMyqOA7sEIpD1O51rNRayTr
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import os
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

DATASET_PATH = "2_port_augmented_dataset_1000.csv"

# __ Loading dataset
df = pd.read_csv(DATASET_PATH)
df.columns = df.columns.str.strip()

print("=" * 50)
print("         DATASET INFO")
print("=" * 50)
print(f"  Total rows loaded : {len(df)}")
print(f"  Columns           : {list(df.columns)}")
print("=" * 50)

# ____ Feature Extraction
# Predict Port 1 output from r2 input
X = df[['r2']].values
y = df[['Port 1']].values.ravel()   # single output → 1D array

# __ Train-Test Splitting
# 80% training, 20% testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"\n  Train samples : {len(X_train)}")
print(f"  Test  samples : {len(X_test)}")

# ___ Training the Model
print("\n  Training Random Forest Model...")
model = RandomForestRegressor(n_estimators=300, random_state=42)
model.fit(X_train, y_train)
print("   Training complete.")

# ___ Evaluating the Model
y_pred = model.predict(X_test)

mse      = mean_squared_error(y_test, y_pred)
rmse     = np.sqrt(mse)
mae      = mean_absolute_error(y_test, y_pred)
r2       = r2_score(y_test, y_pred)
accuracy = r2 * 100

print("\n" + "=" * 50)
print("   Model Evaluation on Test Data")
print("=" * 50)
print(f"  Train samples : {len(X_train)}")
print(f"  Test  samples : {len(X_test)}")
print(f"  MSE           : {mse:.6f}")
print(f"  RMSE          : {rmse:.6f}")
print(f"  MAE           : {mae:.6f}")
print(f"  R² Score      : {r2:.6f}")
print(f"  Accuracy      : {accuracy:.2f}%")
print("=" * 50)

# __ Saving the Model
os.makedirs("model", exist_ok=True)
joblib.dump(model, "model/rf_model_wilkinson2port.pkl")
print("\n   Model saved to 'model/rf_model_wilkinson2port.pkl'")

# __ Results DataFrame
result_df = pd.DataFrame({
    'r2'          : X_test.flatten(),
    'port1_actual': y_test,
    'port1_pred'  : y_pred
})

print(f"\nPredicted vs Actual Test Set (first 10 of {len(result_df)} rows):")
print(result_df[['r2', 'port1_actual', 'port1_pred']].head(10).to_string(index=False))

# __ Plotting
sample_idx = np.arange(len(X_test))

plt.figure(figsize=(10, 5))
plt.plot(sample_idx, result_df['port1_actual'].values, 'o-',
         label='Actual',    markersize=3, linewidth=1)
plt.plot(sample_idx, result_df['port1_pred'].values,   'x--',
         label='Predicted', markersize=3, linewidth=1)
plt.title(f"2-Port Wilkinson Power Combiner — Port 1 Actual vs Predicted  (test n={len(X_test)})")
plt.xlabel("Sample Index")
plt.ylabel("Port 1 Value")
plt.legend()
plt.grid(True, alpha=0.4)
plt.tight_layout()

os.makedirs("plots", exist_ok=True)
plt.savefig("plots/training_plot_wilkinson2port.png", dpi=150)
plt.show()
print("\n   Training plot saved to 'plots/training_plot_wilkinson2port.png'")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import os
from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

DATASET_PATH = "2_port_augmented_dataset_1000.csv"

# __ Loading dataset
df = pd.read_csv(DATASET_PATH)
df.columns = df.columns.str.strip()

print("=" * 50)
print("         DATASET INFO")
print("=" * 50)
print(f"  Total rows loaded : {len(df)}")
print(f"  Columns           : {list(df.columns)}")
print("=" * 50)

# __ Feature Extraction
X = df[['r2']].values
y = df[['Port 1']].values.ravel()

# __ Train-Test Splitting
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"\n  Train samples : {len(X_train)}")
print(f"  Test  samples : {len(X_test)}")

# _ Training the Model
print("\n  Training AdaBoost Regression Model...")

base_estimator = DecisionTreeRegressor(max_depth=4)

model = AdaBoostRegressor(
    estimator=base_estimator,
    n_estimators=300,
    learning_rate=0.1,
    loss='linear',
    random_state=42
)
model.fit(X_train, y_train)
print("   Training complete.")

# _ Evaluating the Model
y_pred = model.predict(X_test)

mse      = mean_squared_error(y_test, y_pred)
rmse     = np.sqrt(mse)
mae      = mean_absolute_error(y_test, y_pred)
r2       = r2_score(y_test, y_pred)
accuracy = r2 * 100

print("\n" + "=" * 50)
print("   Model Evaluation on Test Data")
print("=" * 50)
print(f"  Train samples : {len(X_train)}")
print(f"  Test  samples : {len(X_test)}")
print(f"  MSE           : {mse:.6f}")
print(f"  RMSE          : {rmse:.6f}")
print(f"  MAE           : {mae:.6f}")
print(f"  R² Score      : {r2:.6f}")
print(f"  Accuracy      : {accuracy:.2f}%")
print("=" * 50)

# __ Saving the Model
os.makedirs("model", exist_ok=True)
joblib.dump(model, "model/adaboost_model_wilkinson2port.pkl")
print("\n   Model saved to 'model/adaboost_model_wilkinson2port.pkl'")

# __ Results DataFrame
result_df = pd.DataFrame({
    'r2'          : X_test.flatten(),
    'port1_actual': y_test,
    'port1_pred'  : y_pred
})

print(f"\nPredicted vs Actual Test Set (first 10 of {len(result_df)} rows):")
print(result_df[['r2', 'port1_actual', 'port1_pred']].head(10).to_string(index=False))

# __ Plotting
sample_idx = np.arange(len(X_test))

plt.figure(figsize=(10, 5))
plt.plot(sample_idx, result_df['port1_actual'].values, 'o-',
         label='Actual',    markersize=3, linewidth=1)
plt.plot(sample_idx, result_df['port1_pred'].values,   'x--',
         label='Predicted', markersize=3, linewidth=1)
plt.title(f"2-Port Wilkinson — Port 1 Actual vs Predicted  (test n={len(X_test)})")
plt.xlabel("Sample Index")
plt.ylabel("Port 1 Value")
plt.legend()
plt.grid(True, alpha=0.4)
plt.tight_layout()

os.makedirs("plots", exist_ok=True)
plt.savefig("plots/training_plot_adaboost_wilkinson2port.png", dpi=150)
plt.show()
print("\n   Training plot saved to 'plots/training_plot_adaboost_wilkinson2port.png'")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import os
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

DATASET_PATH = "2_port_augmented_dataset_1000.csv"

# __ Loading dataset
df = pd.read_csv(DATASET_PATH)
df.columns = df.columns.str.strip()

print("=" * 50)
print("         DATASET INFO")
print("=" * 50)
print(f"  Total rows loaded : {len(df)}")
print(f"  Columns           : {list(df.columns)}")
print("=" * 50)

# __ Feature Extraction
X = df[['r2']].values
y = df[['Port 1']].values.ravel()

# __ Train-Test Splitting
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"\n  Train samples : {len(X_train)}")
print(f"  Test  samples : {len(X_test)}")

# _ Training the Model
print("\n  Training Linear Regression Model...")

model = LinearRegression()
model.fit(X_train, y_train)
print("   Training complete.")
print(f"  Coefficient   : {model.coef_[0]:.6f}")
print(f"  Intercept     : {model.intercept_:.6f}")

# _ Evaluating the Model
y_pred = model.predict(X_test)

mse      = mean_squared_error(y_test, y_pred)
rmse     = np.sqrt(mse)
mae      = mean_absolute_error(y_test, y_pred)
r2       = r2_score(y_test, y_pred)
accuracy = r2 * 100

print("\n" + "=" * 50)
print("   Model Evaluation on Test Data")
print("=" * 50)
print(f"  Train samples : {len(X_train)}")
print(f"  Test  samples : {len(X_test)}")
print(f"  MSE           : {mse:.6f}")
print(f"  RMSE          : {rmse:.6f}")
print(f"  MAE           : {mae:.6f}")
print(f"  R² Score      : {r2:.6f}")
print(f"  Accuracy      : {accuracy:.2f}%")
print("=" * 50)

# __ Saving the Model
os.makedirs("model", exist_ok=True)
joblib.dump(model, "model/linear_model_wilkinson2port.pkl")
print("\n   Model saved to 'model/linear_model_wilkinson2port.pkl'")

# __ Results DataFrame
result_df = pd.DataFrame({
    'r2'          : X_test.flatten(),
    'port1_actual': y_test,
    'port1_pred'  : y_pred
})

print(f"\nPredicted vs Actual Test Set (first 10 of {len(result_df)} rows):")
print(result_df[['r2', 'port1_actual', 'port1_pred']].head(10).to_string(index=False))

# __ Plotting
sample_idx = np.arange(len(X_test))

plt.figure(figsize=(10, 5))
plt.plot(sample_idx, result_df['port1_actual'].values, 'o-',
         label='Actual',    markersize=3, linewidth=1)
plt.plot(sample_idx, result_df['port1_pred'].values,   'x--',
         label='Predicted', markersize=3, linewidth=1)
plt.title(f"2-Port Wilkinson — Port 1 Actual vs Predicted  (test n={len(X_test)})")
plt.xlabel("Sample Index")
plt.ylabel("Port 1 Value")
plt.legend()
plt.grid(True, alpha=0.4)
plt.tight_layout()

os.makedirs("plots", exist_ok=True)
plt.savefig("plots/training_plot_linear_wilkinson2port.png", dpi=150)
plt.show()
print("\n   Training plot saved to 'plots/training_plot_linear_wilkinson2port.png'")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import os
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

DATASET_PATH = "2_port_augmented_dataset_1000.csv"

# __ Loading dataset
df = pd.read_csv(DATASET_PATH)
df.columns = df.columns.str.strip()

print("=" * 50)
print("         DATASET INFO")
print("=" * 50)
print(f"  Total rows loaded : {len(df)}")
print(f"  Columns           : {list(df.columns)}")
print("=" * 50)

# __ Feature Extraction
X = df[['r2']].values
y = df[['Port 1']].values.ravel()

# __ Train-Test Splitting
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"\n  Train samples : {len(X_train)}")
print(f"  Test  samples : {len(X_test)}")

# __ Feature Scaling (mandatory for SVR)
scaler_X = StandardScaler()
scaler_y = StandardScaler()

X_train_scaled = scaler_X.fit_transform(X_train)
X_test_scaled  = scaler_X.transform(X_test)

y_train_scaled = scaler_y.fit_transform(y_train.reshape(-1, 1)).ravel()

# _ Training the Model
print("\n  Training SVR Model...")

model = SVR(
    kernel='rbf',    # kernel: 'rbf' | 'linear' | 'poly' | 'sigmoid'
    C=100,           # regularization: higher = less margin, fits data closer
    epsilon=0.01,    # tolerance tube around prediction; smaller = stricter fit
    gamma='scale'    # kernel coefficient: 'scale' | 'auto' | float
)
model.fit(X_train_scaled, y_train_scaled)
print("   Training complete.")

# _ Evaluating the Model
y_pred_scaled = model.predict(X_test_scaled)
y_pred = scaler_y.inverse_transform(y_pred_scaled.reshape(-1, 1)).ravel()

mse      = mean_squared_error(y_test, y_pred)
rmse     = np.sqrt(mse)
mae      = mean_absolute_error(y_test, y_pred)
r2       = r2_score(y_test, y_pred)
accuracy = r2 * 100

print("\n" + "=" * 50)
print("   Model Evaluation on Test Data")
print("=" * 50)
print(f"  Train samples : {len(X_train)}")
print(f"  Test  samples : {len(X_test)}")
print(f"  MSE           : {mse:.6f}")
print(f"  RMSE          : {rmse:.6f}")
print(f"  MAE           : {mae:.6f}")
print(f"  R² Score      : {r2:.6f}")
print(f"  Accuracy      : {accuracy:.2f}%")
print("=" * 50)

# __ Saving the Model and Scalers
os.makedirs("model", exist_ok=True)
joblib.dump(model,    "model/svr_model_wilkinson2port.pkl")
joblib.dump(scaler_X, "model/svr_scaler_X.pkl")
joblib.dump(scaler_y, "model/svr_scaler_y.pkl")
print("\n   Model saved to 'model/svr_model_wilkinson2port.pkl'")
print("   Scalers saved to 'model/svr_scaler_X.pkl' & 'svr_scaler_y.pkl'")

# __ Results DataFrame
result_df = pd.DataFrame({
    'r2'          : X_test.flatten(),
    'port1_actual': y_test,
    'port1_pred'  : y_pred
})

print(f"\nPredicted vs Actual Test Set (first 10 of {len(result_df)} rows):")
print(result_df[['r2', 'port1_actual', 'port1_pred']].head(10).to_string(index=False))

# __ Plotting
sample_idx = np.arange(len(X_test))

plt.figure(figsize=(10, 5))
plt.plot(sample_idx, result_df['port1_actual'].values, 'o-',
         label='Actual',    markersize=3, linewidth=1)
plt.plot(sample_idx, result_df['port1_pred'].values,   'x--',
         label='Predicted', markersize=3, linewidth=1)
plt.title(f"2-Port Wilkinson — Port 1 Actual vs Predicted  (test n={len(X_test)})")
plt.xlabel("Sample Index")
plt.ylabel("Port 1 Value")
plt.legend()
plt.grid(True, alpha=0.4)
plt.tight_layout()

os.makedirs("plots", exist_ok=True)
plt.savefig("plots/training_plot_svr_wilkinson2port.png", dpi=150)
plt.show()
print("\n   Training plot saved to 'plots/training_plot_svr_wilkinson2port.png'")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import os

# ___________Loading the model
# Dataset is loaded only for plotting — not required for prediction itself.
# Used to show the training curve alongside the predicted point.

MODEL_PATH   = "model/rf_model.pkl"
DATASET_PATH = "2_port_augmented_dataset_1000.csv"

if not os.path.exists(MODEL_PATH):
    print("=" * 50)
    print("   Model not found!")
    print("  Please run 'train.py' first.")
    print("=" * 50)
    exit()

model = joblib.load(MODEL_PATH)
print("=" * 50)
print("   Model loaded from 'model/poly_ridge_model.pkl'")
print("=" * 50)

# ___________Load training dataset for plotting
df_train = None
if os.path.exists(DATASET_PATH):
    df_train = pd.read_csv(DATASET_PATH)
    df_train.columns = df_train.columns.str.strip()

# ___________Trained r2 range (from dataset)
R2_MIN = 0.02
R2_MAX = 0.30

# ___________Prediction function
def predict_port(r2_val):
    """Run model prediction for a single r2 value and display result."""
    user_X     = np.array([[r2_val]])
    prediction = model.predict(user_X)[0]

    print("\n" + "=" * 50)
    print("         PORT PREDICTION RESULTS")
    print("=" * 50)
    print(f"  Input r2       : {r2_val}")
    print("-" * 50)
    print(f"  {'Port':<12} {'Predicted Value':>20}")
    print("-" * 50)
    print(f"  {'Port 1':<12} {prediction:>20.6f}")
    print("=" * 50)
    return prediction

# ___________Plotting the predicted result
def plot_prediction(r2_val, prediction):
    """Plot predicted value against training data curve."""
    fig, ax = plt.subplots(figsize=(10, 5))
    fig.suptitle(f"User Prediction  |  r2 = {r2_val}", fontsize=13, fontweight='bold')

    if df_train is not None:
        df_sorted = df_train.sort_values('r2')
        ax.plot(df_sorted['r2'].values, df_sorted['Port 1'].values,
                color='steelblue', alpha=0.6, linewidth=1.5,
                label='Training data')

        # Green vertical line at the input r2
        ax.axvline(r2_val, color='green', linewidth=1.5,
                    linestyle=':', label=f'r2 = {r2_val}')

    # Red horizontal dashed line at the predicted value level
    ax.axhline(prediction, color='red', linewidth=1.5,
               linestyle='--', alpha=0.5, label=f'Predicted: {prediction:.4f}')

    # Red dot at the exact predicted point (intersection)
    ax.plot(r2_val, prediction,
            'o',
            color='red',
            markersize=10,
            zorder=5,
            label=f'▶ Point: ({r2_val}, {prediction:.4f})')

    # Annotate the dot with its value
    ax.annotate(f'  {prediction:.4f}',
                xy=(r2_val, prediction),
                fontsize=9,
                color='red',
                fontweight='bold',
                va='bottom')

    ax.set_title("Port 1 — Actual vs Predicted Point")
    ax.set_xlabel("r2")
    ax.set_ylabel("Port 1 Value")
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.4)

    plt.tight_layout()
    os.makedirs("plots", exist_ok=True)
    save_path = "plots/user_prediction.png"
    plt.savefig(save_path, dpi=150)
    plt.show()
    plt.pause(0.1) # Brief pause to allow Colab to render
    print(f"   Plot saved to '{save_path}'")


# ___________Batch prediction from CSV
def predict_from_csv(csv_path):
    """Batch predict from a CSV file containing an r2 column."""
    if not os.path.exists(csv_path):
        print(f"   File not found: {csv_path}")
        return

    batch_df = pd.read_csv(csv_path)
    batch_df.columns = batch_df.columns.str.strip()

    if 'r2' not in batch_df.columns:
        print("   CSV must contain an 'r2' column.")
        return

    out_of_range = batch_df[
        (batch_df['r2'] < R2_MIN) | (batch_df['r2'] > R2_MAX)
    ]
    if len(out_of_range) > 0:
        print(f"\n   Warning: {len(out_of_range)} rows have r2 outside"
              f" trained range [{R2_MIN} – {R2_MAX}]. Predictions may be inaccurate.")

    X_batch = batch_df[['r2']].values
    preds   = model.predict(X_batch)

    output_df = batch_df[['r2']].copy()
    output_df['port1_pred'] = preds

    save_path = "model/batch_predictions.csv"
    output_df.to_csv(save_path, index=False)

    print(f"\n   Batch predictions saved to '{save_path}'")
    print(output_df.to_string(index=False))


# ___________Main menu
while True:
    print("\n  Options:")
    print("    [1] Single prediction  (enter r2 manually)")
    print("    [2] Batch prediction   (load a CSV file)")
    print("    [3] Exit")

    choice = input("\nSelect option (1 / 2 / 3): ").strip()

    if choice == '1':
        while True:
            r2_input = input("\n  Enter r2 value (or 'back' to return): ").strip()
            if r2_input.lower() == 'back':
                break
            try:
                r2_val = float(r2_input)
            except ValueError:
                print("  Invalid value. Please enter a number.")
                continue

            if not (R2_MIN <= r2_val <= R2_MAX):
                print(f"\n  Warning: r2={r2_val} is outside the trained range"
                      f" [{R2_MIN} – {R2_MAX}]. Prediction may be inaccurate.")

            prediction = predict_port(r2_val)

            show_plot = input("\n  Show prediction plot? (y/n): ").strip().lower()
            if show_plot == 'y':
                plot_prediction(r2_val, prediction)
                plt.close('all') # Clean up plot memory

            again = input("\n  Predict again? (y/n): ").strip().lower()
            if again != 'y':
                break

    elif choice == '2':
        csv_path = input("\n  Enter path to CSV file: ").strip()
        predict_from_csv(csv_path)

    elif choice == '3':
        print("\n  Goodbye!")
        break

    else:
        print("  Invalid choice. Please enter 1, 2, or 3.")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import os

# ___________Loading the model
MODEL_PATH   = "model/rf_model_wilkinson2port.pkl"
DATASET_PATH = "2_port_augmented_dataset_1000.csv"

if not os.path.exists(MODEL_PATH):
    print("=" * 50)
    print("   Model not found!")
    print("  Please run 'train.py' first.")
    print("=" * 50)
    exit()

model = joblib.load(MODEL_PATH)
print("=" * 50)
print("   Model loaded from 'model/rf_model_wilkinson2port.pkl'")
print("=" * 50)

# ___________Load training dataset for plotting
df_train = None
if os.path.exists(DATASET_PATH):
    df_train = pd.read_csv(DATASET_PATH)
    df_train.columns = df_train.columns.str.strip()

# ___________Trained r2 range (from dataset)
if df_train is not None:
    R2_MIN = df_train['r2'].min()
    R2_MAX = df_train['r2'].max()
else:
    R2_MIN = 0.02   # fallback defaults
    R2_MAX = 0.30

print(f"  Trained r2 range : [{R2_MIN} – {R2_MAX}]")

# ___________Prediction function
def predict_port(r2_val):
    """Run model prediction for a single r2 value and display result."""
    user_X     = np.array([[r2_val]])
    prediction = model.predict(user_X)[0]

    print("\n" + "=" * 50)
    print("         PORT PREDICTION RESULTS")
    print("=" * 50)
    print(f"  Input r2       : {r2_val}")
    print("-" * 50)
    print(f"  {'Port':<12} {'Predicted Value':>20}")
    print("-" * 50)
    print(f"  {'Port 1':<12} {prediction:>20.6f}")
    print("=" * 50)
    return prediction

# ___________Plotting the predicted result
def plot_prediction(r2_val, prediction):
    """Plot predicted value against training data curve."""
    fig, ax = plt.subplots(figsize=(10, 5))
    fig.suptitle(
        f"2-Port Wilkinson Power Combiner  |  r2 = {r2_val}",
        fontsize=13, fontweight='bold'
    )

    if df_train is not None:
        df_sorted = df_train.sort_values('r2')
        ax.plot(df_sorted['r2'].values, df_sorted['Port 1'].values,
                color='steelblue', alpha=0.6, linewidth=1.5,
                label='Training data')

    # Green vertical line at the input r2
    ax.axvline(r2_val, color='green', linewidth=1.5,
               linestyle=':', label=f'r2 = {r2_val}')

    # Red horizontal dashed line at the predicted value level
    ax.axhline(prediction, color='red', linewidth=1.5,
               linestyle='--', alpha=0.5, label=f'Predicted: {prediction:.4f}')

    # Red dot at the exact predicted point (intersection)
    ax.plot(r2_val, prediction,
            'o', color='red', markersize=10, zorder=5,
            label=f'▶ Point: ({r2_val}, {prediction:.4f})')

    # Annotate the dot with its value
    ax.annotate(f'  {prediction:.4f}',
                xy=(r2_val, prediction),
                fontsize=9, color='red', fontweight='bold', va='bottom')

    ax.set_title("2-Port Wilkinson — Port 1  |  Training Data vs Predicted Point")
    ax.set_xlabel("r2")
    ax.set_ylabel("Port 1 Value")
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.4)

    plt.tight_layout()
    os.makedirs("plots", exist_ok=True)
    save_path = "plots/user_prediction_wilkinson2port.png"
    plt.savefig(save_path, dpi=150)
    plt.show()
    plt.pause(0.1)
    print(f"   Plot saved to '{save_path}'")


# ___________Batch prediction from CSV
def predict_from_csv(csv_path):
    """Batch predict from a CSV file containing an r2 column."""
    if not os.path.exists(csv_path):
        print(f"   File not found: {csv_path}")
        return

    batch_df = pd.read_csv(csv_path)
    batch_df.columns = batch_df.columns.str.strip()

    if 'r2' not in batch_df.columns:
        print("   CSV must contain an 'r2' column.")
        return

    out_of_range = batch_df[
        (batch_df['r2'] < R2_MIN) | (batch_df['r2'] > R2_MAX)
    ]
    if len(out_of_range) > 0:
        print(f"\n   Warning: {len(out_of_range)} rows have r2 outside"
              f" trained range [{R2_MIN} – {R2_MAX}]. Predictions may be inaccurate.")

    X_batch = batch_df[['r2']].values
    preds   = model.predict(X_batch)

    output_df = batch_df[['r2']].copy()
    output_df['port1_pred'] = preds

    os.makedirs("model", exist_ok=True)
    save_path = "model/batch_predictions_wilkinson2port.csv"
    output_df.to_csv(save_path, index=False)

    print(f"\n   Batch predictions saved to '{save_path}'")
    print(output_df.to_string(index=False))


# ___________Main menu
while True:
    print("\n  Options:")
    print("    [1] Single prediction  (enter r2 manually)")
    print("    [2] Batch prediction   (load a CSV file)")
    print("    [3] Exit")

    choice = input("\nSelect option (1 / 2 / 3): ").strip()

    if choice == '1':
        while True:
            r2_input = input("\n  Enter r2 value (or 'back' to return): ").strip()
            if r2_input.lower() == 'back':
                break
            try:
                r2_val = float(r2_input)
            except ValueError:
                print("  Invalid value. Please enter a number.")
                continue

            if not (R2_MIN <= r2_val <= R2_MAX):
                print(f"\n  Warning: r2={r2_val} is outside the trained range"
                      f" [{R2_MIN} – {R2_MAX}]. Prediction may be inaccurate.")

            prediction = predict_port(r2_val)

            show_plot = input("\n  Show prediction plot? (y/n): ").strip().lower()
            if show_plot == 'y':
                plot_prediction(r2_val, prediction)
                plt.close('all')

            again = input("\n  Predict again? (y/n): ").strip().lower()
            if again != 'y':
                break

    elif choice == '2':
        csv_path = input("\n  Enter path to CSV file: ").strip()
        predict_from_csv(csv_path)

    elif choice == '3':
        print("\n  Goodbye!")
        break

    else:
        print("  Invalid choice. Please enter 1, 2, or 3.")