# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Oo5AtY5HnLP92dkQ1OfT4apAQ2uwrGL
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import os
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

DATASET_PATH = "4port_datasetaug_1000.csv"

# ______ Loaing dataset
df = pd.read_csv(DATASET_PATH)
df.columns = df.columns.str.strip()

print("=" * 50)
print("         DATASET INFO")
print("=" * 50)
print(f"  Total rows loaded : {len(df)}")
print(f"  Columns           : {list(df.columns)}")
print("=" * 50)

#  __________ feature Extraction
# here we extract the features for predict
X = df[['r2']].values
y = df[['port1', 'port2', 'port3', 'port4']].values

# ______Train test splitting
# here splits 80% data for training and 20% data for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"\n  Train samples : {len(X_train)}")
print(f"  Test  samples : {len(X_test)}")

# _______Training the model

print("\n  Training Random Forest Model...")
model = MultiOutputRegressor(
    RandomForestRegressor(n_estimators=300, random_state=42)
)
model.fit(X_train, y_train)
print("   Training complete.")

# _________Evaluating the model
y_pred = model.predict(X_test)

mse      = mean_squared_error(y_test, y_pred)
rmse     = np.sqrt(mse)
mae      = mean_absolute_error(y_test, y_pred)
r2       = r2_score(y_test, y_pred)
accuracy = r2 * 100
print("\n" + "=" * 50)
print("   Model Evaluation on Test Data")
print("=" * 50)
print(f"  Train samples : {len(X_train)}")
print(f"  Test  samples : {len(X_test)}")
print(f"  MSE           : {mse:.6f}")
print(f"  RMSE          : {rmse:.6f}")
print(f"  MAE           : {mae:.6f}")
print(f"  R² Score      : {r2:.6f}")
print(f"  Accuracy      : {accuracy:.2f}%")
print("=" * 50)

# ______Saving the model
os.makedirs("model", exist_ok=True)
joblib.dump(model, "model/rf_model.pkl")
print("\n   Model saved to 'model/rf_model.pkl'")

# Ploting the results
result_df = pd.DataFrame(
    y_pred,
    columns=['port1_pred', 'port2_pred', 'port3_pred', 'port4_pred']
)
result_df[['port1_actual', 'port2_actual', 'port3_actual', 'port4_actual']] = y_test
result_df['r2'] = X_test.flatten()

print(f"\nPredicted vs Actual Test Set (first 10 of {len(result_df)} rows):")
print(result_df[['r2',
                  'port1_actual', 'port1_pred',
                  'port2_actual', 'port2_pred',
                  'port3_actual', 'port3_pred',
                  'port4_actual', 'port4_pred']].head(10).to_string(index=False))
ports      = ['port1', 'port2', 'port3', 'port4']
sample_idx = np.arange(len(X_test))
plt.figure(figsize=(16, 10))
for i, port in enumerate(ports, 1):
    plt.subplot(2, 2, i)
    actual    = result_df[f'{port}_actual'].values
    predicted = result_df[f'{port}_pred'].values
    plt.plot(sample_idx, actual,    'o-',  label='Actual',    markersize=2, linewidth=1)
    plt.plot(sample_idx, predicted, 'x--', label='Predicted', markersize=2, linewidth=1)
    plt.title(f"{port} Actual vs Predicted  (test n={len(X_test)})")
    plt.xlabel("Sample Index")
    plt.ylabel("Value")
    plt.legend()
    plt.grid(True, alpha=0.4)

plt.tight_layout()
os.makedirs("plots", exist_ok=True)
plt.savefig("plots/training_plot.png", dpi=150)
plt.show()
print("\n   Training plot saved to 'plots/training_plot.png'")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import os

# ___________Loading the model
MODEL_PATH   = "model/rf_model.pkl"
DATASET_PATH = "4port_datasetaug_1000.csv"

if not os.path.exists(MODEL_PATH):
    print("=" * 50)
    print("   Model not found!")
    print("  Please run 'train.py' first.")
    print("=" * 50)
    exit()

model = joblib.load(MODEL_PATH)
print("=" * 50)
print("   Model loaded from 'model/rf_model.pkl'")
print("=" * 50)

# ___________Load training dataset for plotting
df_train = None
if os.path.exists(DATASET_PATH):
    df_train = pd.read_csv(DATASET_PATH)
    df_train.columns = df_train.columns.str.strip()

# ___________Trained r2 range (auto-derived from dataset)
if df_train is not None:
    R2_MIN = df_train['r2'].min()
    R2_MAX = df_train['r2'].max()
else:
    R2_MIN = 0.02   # fallback defaults
    R2_MAX = 0.30

print(f"  Trained r2 range : [{R2_MIN} – {R2_MAX}]")

PORTS = ['port1', 'port2', 'port3', 'port4']

# ___________Prediction function
def predict_ports(r2_val):
    """Run model prediction for a single r2 value and display results."""
    user_X      = np.array([[r2_val]])
    predictions = model.predict(user_X)[0]   # shape: (4,)

    print("\n" + "=" * 50)
    print("         PORT PREDICTION RESULTS")
    print("=" * 50)
    print(f"  Input r2       : {r2_val}")
    print("-" * 50)
    print(f"  {'Port':<12} {'Predicted Value':>20}")
    print("-" * 50)
    for port, val in zip(PORTS, predictions):
        print(f"  {port.capitalize():<12} {val:>20.6f}")
    print("=" * 50)
    return predictions


# ___________Plotting the predicted result
def plot_prediction(r2_val, predictions):
    """Plot predicted values against training data curves for all 4 ports."""
    fig, axes = plt.subplots(2, 2, figsize=(14, 8))
    fig.suptitle(
        f"4-Port Power Combiner  |  r2 = {r2_val}",
        fontsize=13, fontweight='bold'
    )
    axes = axes.flatten()

    for i, (port, pred_val) in enumerate(zip(PORTS, predictions)):
        ax = axes[i]

        if df_train is not None:
            df_sorted = df_train.sort_values('r2')
            ax.plot(df_sorted['r2'].values, df_sorted[port].values,
                    color='steelblue', alpha=0.6, linewidth=1.5,
                    label='Training data')

        # Green vertical line at the input r2
        ax.axvline(r2_val, color='green', linewidth=1.5,
                   linestyle=':', label=f'r2 = {r2_val}')

        # Red horizontal dashed line at the predicted value level
        ax.axhline(pred_val, color='red', linewidth=1.5,
                   linestyle='--', alpha=0.5, label=f'Predicted: {pred_val:.4f}')

        # Red dot at the exact predicted point (intersection)
        ax.plot(r2_val, pred_val,
                'o', color='red', markersize=10, zorder=5,
                label=f'▶ Point: ({r2_val}, {pred_val:.4f})')

        # Annotate the dot with its value
        ax.annotate(f'  {pred_val:.4f}',
                    xy=(r2_val, pred_val),
                    fontsize=9, color='red', fontweight='bold', va='bottom')

        ax.set_title(f"{port.capitalize()} — Training Data vs Predicted Point")
        ax.set_xlabel("r2")
        ax.set_ylabel(f"{port.capitalize()} Value")
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.4)

    plt.tight_layout()
    os.makedirs("plots", exist_ok=True)
    save_path = "plots/user_prediction_4port.png"
    plt.savefig(save_path, dpi=150)
    plt.show()
    plt.pause(0.1)
    print(f"   Plot saved to '{save_path}'")


# ___________Batch prediction from CSV
def predict_from_csv(csv_path):
    """Batch predict from a CSV file containing an r2 column."""
    if not os.path.exists(csv_path):
        print(f"   File not found: {csv_path}")
        return

    batch_df = pd.read_csv(csv_path)
    batch_df.columns = batch_df.columns.str.strip()

    if 'r2' not in batch_df.columns:
        print("   CSV must contain an 'r2' column.")
        return

    out_of_range = batch_df[
        (batch_df['r2'] < R2_MIN) | (batch_df['r2'] > R2_MAX)
    ]
    if len(out_of_range) > 0:
        print(f"\n   Warning: {len(out_of_range)} rows have r2 outside"
              f" trained range [{R2_MIN} – {R2_MAX}]. Predictions may be inaccurate.")

    X_batch = batch_df[['r2']].values
    preds   = model.predict(X_batch)   # shape: (n_rows, 4)

    output_df = batch_df[['r2']].copy()
    for i, port in enumerate(PORTS):
        output_df[f'{port}_pred'] = preds[:, i]

    os.makedirs("model", exist_ok=True)
    save_path = "model/batch_predictions_4port.csv"
    output_df.to_csv(save_path, index=False)

    print(f"\n   Batch predictions saved to '{save_path}'")
    print(output_df.to_string(index=False))


# ___________Main menu
while True:
    print("\n  Options:")
    print("    [1] Single prediction  (enter r2 manually)")
    print("    [2] Batch prediction   (load a CSV file)")
    print("    [3] Exit")

    choice = input("\nSelect option (1 / 2 / 3): ").strip()

    if choice == '1':
        while True:
            r2_input = input("\n  Enter r2 value (or 'back' to return): ").strip()
            if r2_input.lower() == 'back':
                break
            try:
                r2_val = float(r2_input)
            except ValueError:
                print("  Invalid value. Please enter a number.")
                continue

            if not (R2_MIN <= r2_val <= R2_MAX):
                print(f"\n  Warning: r2={r2_val} is outside the trained range"
                      f" [{R2_MIN} – {R2_MAX}]. Prediction may be inaccurate.")

            predictions = predict_ports(r2_val)

            show_plot = input("\n  Show prediction plot? (y/n): ").strip().lower()
            if show_plot == 'y':
                plot_prediction(r2_val, predictions)
                plt.close('all')

            again = input("\n  Predict again? (y/n): ").strip().lower()
            if again != 'y':
                break

    elif choice == '2':
        csv_path = input("\n  Enter path to CSV file: ").strip()
        predict_from_csv(csv_path)

    elif choice == '3':
        print("\n  Goodbye!")
        break

    else:
        print("  Invalid choice. Please enter 1, 2, or 3.")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import os
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

DATASET_PATH = "4port_datasetaug_1000.csv"

# ______ Loading dataset
df = pd.read_csv(DATASET_PATH)
df.columns = df.columns.str.strip()

print("=" * 50)
print("         DATASET INFO")
print("=" * 50)
print(f"  Total rows loaded : {len(df)}")
print(f"  Columns           : {list(df.columns)}")
print("=" * 50)

# __________ Feature Extraction
X = df[['r2']].values
y = df[['port1', 'port2', 'port3', 'port4']].values

# ______ Train/Test Split (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"\n  Train samples : {len(X_train)}")
print(f"  Test  samples : {len(X_test)}")

# _______ Training the AdaBoost Model
print("\n  Training AdaBoost Model...")
base_estimator = DecisionTreeRegressor(max_depth=4)

model = MultiOutputRegressor(
    AdaBoostRegressor(
        estimator=base_estimator,
        n_estimators=300,
        learning_rate=0.1,
        random_state=42
    )
)
model.fit(X_train, y_train)
print("   Training complete.")

# _________ Evaluating the Model
y_pred = model.predict(X_test)

mse      = mean_squared_error(y_test, y_pred)
rmse     = np.sqrt(mse)
mae      = mean_absolute_error(y_test, y_pred)
r2       = r2_score(y_test, y_pred)
accuracy = r2 * 100

print("\n" + "=" * 50)
print("   Model Evaluation on Test Data")
print("=" * 50)
print(f"  Train samples : {len(X_train)}")
print(f"  Test  samples : {len(X_test)}")
print(f"  MSE           : {mse:.6f}")
print(f"  RMSE          : {rmse:.6f}")
print(f"  MAE           : {mae:.6f}")
print(f"  R² Score      : {r2:.6f}")
print(f"  Accuracy      : {accuracy:.2f}%")
print("=" * 50)

# ______ Saving the Model
os.makedirs("model", exist_ok=True)
joblib.dump(model, "model/adaboost_model.pkl")
print("\n   Model saved to 'model/adaboost_model.pkl'")

# ______ Plotting the Results
result_df = pd.DataFrame(
    y_pred,
    columns=['port1_pred', 'port2_pred', 'port3_pred', 'port4_pred']
)
result_df[['port1_actual', 'port2_actual', 'port3_actual', 'port4_actual']] = y_test
result_df['r2'] = X_test.flatten()

print(f"\nPredicted vs Actual Test Set (first 10 of {len(result_df)} rows):")
print(result_df[['r2',
                  'port1_actual', 'port1_pred',
                  'port2_actual', 'port2_pred',
                  'port3_actual', 'port3_pred',
                  'port4_actual', 'port4_pred']].head(10).to_string(index=False))

ports      = ['port1', 'port2', 'port3', 'port4']
sample_idx = np.arange(len(X_test))

plt.figure(figsize=(16, 10))
for i, port in enumerate(ports, 1):
    plt.subplot(2, 2, i)
    actual    = result_df[f'{port}_actual'].values
    predicted = result_df[f'{port}_pred'].values
    plt.plot(sample_idx, actual,    'o-',  label='Actual',    markersize=2, linewidth=1)
    plt.plot(sample_idx, predicted, 'x--', label='Predicted', markersize=2, linewidth=1)
    plt.title(f"{port} Actual vs Predicted  (test n={len(X_test)})")
    plt.xlabel("Sample Index")
    plt.ylabel("Value")
    plt.legend()
    plt.grid(True, alpha=0.4)

plt.tight_layout()
os.makedirs("plots", exist_ok=True)
plt.savefig("plots/adaboost_training_plot.png", dpi=150)
plt.show()
print("\n   Training plot saved to 'plots/adaboost_training_plot.png'")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import os
from sklearn.multioutput import MultiOutputRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

DATASET_PATH = "4port_datasetaug_1000.csv"

# ______ Loading dataset
df = pd.read_csv(DATASET_PATH)
df.columns = df.columns.str.strip()

print("=" * 50)
print("         DATASET INFO")
print("=" * 50)
print(f"  Total rows loaded : {len(df)}")
print(f"  Columns           : {list(df.columns)}")
print("=" * 50)

# __________ Feature Extraction
X = df[['r2']].values
y = df[['port1', 'port2', 'port3', 'port4']].values

# ______ Train/Test Split (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"\n  Train samples : {len(X_train)}")
print(f"  Test  samples : {len(X_test)}")

# _______ Training the SVM Model
print("\n  Training SVM (SVR) Model...")

# SVR requires feature scaling — Pipeline handles it cleanly
svr_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('svr', SVR(
        kernel='rbf',      # Radial Basis Function kernel (best for nonlinear data)
        C=100,             # Regularization: higher = less margin, fits data closer
        epsilon=0.01,      # Tube width: predictions within epsilon incur no penalty
        gamma='scale'      # Kernel coefficient: 'scale' = 1/(n_features * X.var())
    ))
])

model = MultiOutputRegressor(svr_pipeline)
model.fit(X_train, y_train)
print("   Training complete.")

# _________ Evaluating the Model
y_pred = model.predict(X_test)

mse      = mean_squared_error(y_test, y_pred)
rmse     = np.sqrt(mse)
mae      = mean_absolute_error(y_test, y_pred)
r2       = r2_score(y_test, y_pred)
accuracy = r2 * 100

print("\n" + "=" * 50)
print("   Model Evaluation on Test Data")
print("=" * 50)
print(f"  Train samples : {len(X_train)}")
print(f"  Test  samples : {len(X_test)}")
print(f"  MSE           : {mse:.6f}")
print(f"  RMSE          : {rmse:.6f}")
print(f"  MAE           : {mae:.6f}")
print(f"  R² Score      : {r2:.6f}")
print(f"  Accuracy      : {accuracy:.2f}%")
print("=" * 50)

# ______ Saving the Model
os.makedirs("model", exist_ok=True)
joblib.dump(model, "model/svm_model.pkl")
print("\n   Model saved to 'model/svm_model.pkl'")

# ______ Plotting the Results
result_df = pd.DataFrame(
    y_pred,
    columns=['port1_pred', 'port2_pred', 'port3_pred', 'port4_pred']
)
result_df[['port1_actual', 'port2_actual', 'port3_actual', 'port4_actual']] = y_test
result_df['r2'] = X_test.flatten()

print(f"\nPredicted vs Actual Test Set (first 10 of {len(result_df)} rows):")
print(result_df[['r2',
                  'port1_actual', 'port1_pred',
                  'port2_actual', 'port2_pred',
                  'port3_actual', 'port3_pred',
                  'port4_actual', 'port4_pred']].head(10).to_string(index=False))

ports      = ['port1', 'port2', 'port3', 'port4']
sample_idx = np.arange(len(X_test))

plt.figure(figsize=(16, 10))
for i, port in enumerate(ports, 1):
    plt.subplot(2, 2, i)
    actual    = result_df[f'{port}_actual'].values
    predicted = result_df[f'{port}_pred'].values
    plt.plot(sample_idx, actual,    'o-',  label='Actual',    markersize=2, linewidth=1)
    plt.plot(sample_idx, predicted, 'x--', label='Predicted', markersize=2, linewidth=1)
    plt.title(f"{port} Actual vs Predicted  (test n={len(X_test)})")
    plt.xlabel("Sample Index")
    plt.ylabel("Value")
    plt.legend()
    plt.grid(True, alpha=0.4)

plt.tight_layout()
os.makedirs("plots", exist_ok=True)
plt.savefig("plots/svm_training_plot.png", dpi=150)
plt.show()
print("\n   Training plot saved to 'plots/svm_training_plot.png'")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import os
from sklearn.multioutput import MultiOutputRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

DATASET_PATH = "4port_datasetaug_1000.csv"

# ______ Loading dataset
df = pd.read_csv(DATASET_PATH)
df.columns = df.columns.str.strip()

print("=" * 50)
print("         DATASET INFO")
print("=" * 50)
print(f"  Total rows loaded : {len(df)}")
print(f"  Columns           : {list(df.columns)}")
print("=" * 50)

# __________ Feature Extraction
X = df[['r2']].values
y = df[['port1', 'port2', 'port3', 'port4']].values

# ______ Train/Test Split (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"\n  Train samples : {len(X_train)}")
print(f"  Test  samples : {len(X_test)}")

# _______ Training the KNN Model
print("\n  Training KNN Regression Model...")

# KNN is distance-based so StandardScaler is required inside Pipeline
knn_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('knn', KNeighborsRegressor(
        n_neighbors=5,          # Number of nearest neighbors to consider
        weights='distance',     # Closer neighbors contribute more than farther ones
        algorithm='auto',       # Auto-selects best tree structure (ball_tree/kd_tree/brute)
        metric='minkowski',     # Distance metric: minkowski with p=2 equals Euclidean
        p=2,                    # p=2 → Euclidean distance, p=1 → Manhattan distance
        n_jobs=-1               # Use all CPU cores for neighbor search
    ))
])

model = MultiOutputRegressor(knn_pipeline)
model.fit(X_train, y_train)
print("   Training complete.")

# _________ Evaluating the Model
y_pred = model.predict(X_test)

mse      = mean_squared_error(y_test, y_pred)
rmse     = np.sqrt(mse)
mae      = mean_absolute_error(y_test, y_pred)
r2       = r2_score(y_test, y_pred)
accuracy = r2 * 100

print("\n" + "=" * 50)
print("   Model Evaluation on Test Data")
print("=" * 50)
print(f"  Train samples : {len(X_train)}")
print(f"  Test  samples : {len(X_test)}")
print(f"  MSE           : {mse:.6f}")
print(f"  RMSE          : {rmse:.6f}")
print(f"  MAE           : {mae:.6f}")
print(f"  R² Score      : {r2:.6f}")
print(f"  Accuracy      : {accuracy:.2f}%")
print("=" * 50)

# ______ Print KNN Model Configuration (unique to KNN)
print("\n  KNN Model Configuration:")
print("=" * 50)
knn_step = model.estimators_[0].named_steps['knn']
print(f"  n_neighbors : {knn_step.n_neighbors}")
print(f"  weights     : {knn_step.weights}")
print(f"  algorithm   : {knn_step.algorithm}")
print(f"  metric      : {knn_step.metric} (p={knn_step.p})")
print(f"  Outputs     : port1, port2, port3, port4")
print("=" * 50)

# ______ Saving the Model
os.makedirs("model", exist_ok=True)
joblib.dump(model, "model/knn_model.pkl")
print("\n   Model saved to 'model/knn_model.pkl'")

# ______ Plotting the Results
result_df = pd.DataFrame(
    y_pred,
    columns=['port1_pred', 'port2_pred', 'port3_pred', 'port4_pred']
)
result_df[['port1_actual', 'port2_actual', 'port3_actual', 'port4_actual']] = y_test
result_df['r2'] = X_test.flatten()

print(f"\nPredicted vs Actual Test Set (first 10 of {len(result_df)} rows):")
print(result_df[['r2',
                  'port1_actual', 'port1_pred',
                  'port2_actual', 'port2_pred',
                  'port3_actual', 'port3_pred',
                  'port4_actual', 'port4_pred']].head(10).to_string(index=False))

ports      = ['port1', 'port2', 'port3', 'port4']
sample_idx = np.arange(len(X_test))

plt.figure(figsize=(16, 10))
for i, port in enumerate(ports, 1):
    plt.subplot(2, 2, i)
    actual    = result_df[f'{port}_actual'].values
    predicted = result_df[f'{port}_pred'].values
    plt.plot(sample_idx, actual,    'o-',  label='Actual',    markersize=2, linewidth=1)
    plt.plot(sample_idx, predicted, 'x--', label='Predicted', markersize=2, linewidth=1)
    plt.title(f"{port} Actual vs Predicted  (test n={len(X_test)})")
    plt.xlabel("Sample Index")
    plt.ylabel("Value")
    plt.legend()
    plt.grid(True, alpha=0.4)

plt.tight_layout()
os.makedirs("plots", exist_ok=True)
plt.savefig("plots/knn_training_plot.png", dpi=150)
plt.show()
print("\n   Training plot saved to 'plots/knn_training_plot.png'")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import os
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

DATASET_PATH = "4port_datasetaug_1000.csv"

# ______ Loading dataset
df = pd.read_csv(DATASET_PATH)
df.columns = df.columns.str.strip()

print("=" * 50)
print("         DATASET INFO")
print("=" * 50)
print(f"  Total rows loaded : {len(df)}")
print(f"  Columns           : {list(df.columns)}")
print("=" * 50)

# __________ Feature Extraction
X = df[['r2']].values
y = df[['port1', 'port2', 'port3', 'port4']].values

# ______ Train/Test Split (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"\n  Train samples : {len(X_train)}")
print(f"  Test  samples : {len(X_test)}")

# _______ Training the Linear Regression Model
print("\n  Training Linear Regression Model...")

# LinearRegression natively supports multi-output — no wrapper needed
model = LinearRegression(
    fit_intercept=True,   # Learns bias/intercept term (always recommended)
    copy_X=True,          # Keeps original X unchanged during fitting
    n_jobs=-1             # Uses all CPU cores for faster computation
)
model.fit(X_train, y_train)
print("   Training complete.")

# _________ Evaluating the Model
y_pred = model.predict(X_test)

mse      = mean_squared_error(y_test, y_pred)
rmse     = np.sqrt(mse)
mae      = mean_absolute_error(y_test, y_pred)
r2       = r2_score(y_test, y_pred)
accuracy = r2 * 100

print("\n" + "=" * 50)
print("   Model Evaluation on Test Data")
print("=" * 50)
print(f"  Train samples : {len(X_train)}")
print(f"  Test  samples : {len(X_test)}")
print(f"  MSE           : {mse:.6f}")
print(f"  RMSE          : {rmse:.6f}")
print(f"  MAE           : {mae:.6f}")
print(f"  R² Score      : {r2:.6f}")
print(f"  Accuracy      : {accuracy:.2f}%")
print("=" * 50)

# ______ Print Learned Coefficients (unique to Linear Regression)
print("\n  Learned Model Coefficients:")
print("=" * 50)
ports = ['port1', 'port2', 'port3', 'port4']
for i, port in enumerate(ports):
    coef      = model.coef_[i][0]
    intercept = model.intercept_[i]
    print(f"  {port} → Coefficient: {coef:.6f}  |  Intercept: {intercept:.6f}")
    print(f"         Equation : {port} = {coef:.6f} * r2 + ({intercept:.6f})")
print("=" * 50)

# ______ Saving the Model
os.makedirs("model", exist_ok=True)
joblib.dump(model, "model/linear_model.pkl")
print("\n   Model saved to 'model/linear_model.pkl'")

# ______ Plotting the Results
result_df = pd.DataFrame(
    y_pred,
    columns=['port1_pred', 'port2_pred', 'port3_pred', 'port4_pred']
)
result_df[['port1_actual', 'port2_actual', 'port3_actual', 'port4_actual']] = y_test
result_df['r2'] = X_test.flatten()

print(f"\nPredicted vs Actual Test Set (first 10 of {len(result_df)} rows):")
print(result_df[['r2',
                  'port1_actual', 'port1_pred',
                  'port2_actual', 'port2_pred',
                  'port3_actual', 'port3_pred',
                  'port4_actual', 'port4_pred']].head(10).to_string(index=False))

ports      = ['port1', 'port2', 'port3', 'port4']
sample_idx = np.arange(len(X_test))

plt.figure(figsize=(16, 10))
for i, port in enumerate(ports, 1):
    plt.subplot(2, 2, i)
    actual    = result_df[f'{port}_actual'].values
    predicted = result_df[f'{port}_pred'].values
    plt.plot(sample_idx, actual,    'o-',  label='Actual',    markersize=2, linewidth=1)
    plt.plot(sample_idx, predicted, 'x--', label='Predicted', markersize=2, linewidth=1)
    plt.title(f"{port} Actual vs Predicted  (test n={len(X_test)})")
    plt.xlabel("Sample Index")
    plt.ylabel("Value")
    plt.legend()
    plt.grid(True, alpha=0.4)

plt.tight_layout()
os.makedirs("plots", exist_ok=True)
plt.savefig("plots/linear_training_plot.png", dpi=150)
plt.show()
print("\n   Training plot saved to 'plots/linear_training_plot.png'")